import { Player } from './player';

/**
 * Game model
 * Represents a game with a unique game code
 * and a list of players
 */
export class Game {
    public gameCode: string; // The game's unique code, as generated by the server
    public players: Player[]; // The list of players in the game
    public isLive: boolean; // Whether the game is live or not

    /**
     * Create a game
     * @param gameCode The game's unique code
     */
    constructor(gameCode: string) {
        this.gameCode = gameCode;
        this.players = [];
        this.isLive = false;
    }

    /**
     * Add a player to the game
     * @param player The player to add
     * @returns Whether the player was added or not
     * @throws Error if the player is already in the game
     * @throws Error if the game is live
     * @throws Error if the player is already in a game
     */
    public addPlayer(player: Player): boolean {
        if (this.isLive) {
            throw new Error("Game is live");
        }
        if (this.players.includes(player)) {
            throw new Error("Player is already in the game");
        }
        if (player.game) {
            throw new Error("Player is already in a game");
        }
        this.players.push(player);
        player.game = this;
        return true;
    }
}
