import { Player } from './player';

/**
 * Game model
 * Represents a game with a unique game code
 * and a list of players
 */
export class Game {
    public gameCode: string; // The game's unique code, as generated by the server
    public players: Player[]; // The list of players in the game
    public isLive: boolean; // Whether the game is live or not
}
